name: PiggyCrates
main: DaPigGuy\PiggyCrates\PiggyCrates
version: 2.0.8
api: 4.0.0
load: POSTWORLD
author: DaPigGuy
softdepend: ["PiggyCustomEnchants"]
website: "https://github.com/DaPigGuy/PiggyCrates/"
permissions:
  piggycrates:
    default: false
    description: "Allows usage of all PiggyCrates features"
  piggycrates.command:
    default: op
    description: "Allow usage of all PiggyCrates commands"
  piggycrates.command.crate:
    default: op
    description: "Allow usage of the /crate command"
  piggycrates.command.key:
    default: op
    description: "Allow usage of the /key command"
  piggycrates.command.keyall:
    default: op
    description: "Allow usage of the /keyall command"
